### ISSUE TITLE
Feature request: add user notes to each move

### ISSUE THREAD

**Issue by lebigot** [herzbube/littlego#267]
It would be very useful if the user could add comments on each move of the game. I want to analyze my games while I play, by taking notes: it would be great if this were possible!

Currently, I would need to take notes in a separate document, and then paste them in the exported SGF, one by one, which is not very nice…

**Comment by herzbube** [comment]
Eric, thanks for the suggestion. This is another one that depends on #112. I'm making this (and #112) prio 1, but I can't say when I will get to implement them. Currently I am working on a new iPhone 6 Plus landscape UI. Also, I have promised to add support for AGA rules, and there is an interesting thing about Game Center integration in the pipeline. But everything's going forward very slow.

**Comment by lebigot** [comment]
Great! Good luck with everything. I am looking forward to the next version. :)

**Comment by herzbube** [comment]
I just opened #339, which is for *displaying* notes/annotations on moves. With direct SGF reading/writing capabilities available (#112 is closed) this is now within reach. Still no promises about a time schedule, though.

**Comment by herzbube** [comment]
In the next release it will be possible to edit all node annotation and move annotation SGF properties, among them the node title property (`N`) and the comment property (`C`). They will be exposed in the UI as the "short description" (node title) and a "long description" (comment) of a node.

The code for this is in commit 1287dee9a3fc8e0e5d600ec93dde5d5ac024a33b.
