### ISSUE TITLE
Add Dark mode support

### ISSUE THREAD

**Issue by herzbube** [herzbube/littlego#345]
Some notes:

- Dark mode was introduced in iOS 13.
- Use traits collections to check for the mode or to react to mode changes.
- UIColor has new colors that adapt dynamically.
- Board position collection view cells / table view cells need to find a new dark mode color scheme.

**Comment by dingbat** [comment]
Hi! I'm not sure how you like to work with collaborators on this project in general, but I'm happy to take this on or help work on this.

**Comment by herzbube** [comment]
@dingbat Thanks for the offer. I didn't see your comment until just now or I would have responded sooner. I have been working on the Dark Mode support feature for the last couple of days and have just now finished with it - all that's left is one final pass over the three UI types to check if I missed something. If not I will close the issue as completed. So - nothing to do here anymore, unless you find a bug or an area that I missed.

I usually push my changes sooner, so apologies if I gave the impression of not being active on this one. By the way, never mind the Git commit dates, they are so close together because I did some rebasing before I pushed.

I'll comment on the other issue that you opened soon'ish.

**Comment by herzbube** [comment]
Yep, looks good.

**Comment by dingbat** [comment]
@herzbube fantastic! Good thing I didn't start on it then. Took a look on the sim and it looks good. Only thing I'll say is that I won't consider dark mode done until there's a darker board theme (the wooden bg is quite bright at night), but board theming definitely sounds like its own feature. Let me know and I can open the issue.

**Comment by herzbube** [comment]
Sure, go ahead and open an issue. To be honest, I went through the motions of adopting Dark Mode rather mechanically because I don't use Dark Mode myself. I just thought it would be a nice exercise to start working with `UITraitCollection`.
